# Generated by Django 4.2.29 on 2026-03-28 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ได้รับสินค้าแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม (฿)')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='ME PRO NID NOI', max_length=200, verbose_name='แบรนด์')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา (฿)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('image_url', models.URLField(blank=True, verbose_name='URL รูปภาพ (ถ้าไม่อัปโหลด)')),
                ('available_sizes', models.CharField(default='S,M,L,XL', max_length=50, verbose_name='ไซส์ที่มี (คั่นด้วย ,)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='จำนวนสต็อก')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า (snapshot)')),
                ('size', models.CharField(max_length=10, verbose_name='ไซส์')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อชิ้น (฿)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
            },
        ),
    ]
